#!/bin/bash
cd "`dirname \"$0\"`"
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > addons.xml
echo "<addons>" >> addons.xml
{
read LINE;
while read LINE; do
  echo "$LINE" >> addons.xml
done 
} < plugin.video.ex.ua.viewer/addon.xml
echo "</addons>" >> addons.xml
md5sum addons.xml | cut -f1 -d' ' > addons.xml.checksum
hg add *
hg commit -u vadim.skorba@gmail.com
hg push -f https://vadim.skorba@ex-ua-viewer.googlecode.com/hg/
